
# Possibility to change the separator between the sortable field and the direction (ASC or DESC). Default value is : (colon) - can be changed to e.g. | by writing
#sort:
#  direction:
#    separator: \|

# Pagination settings
pagination:
#  # encryptionKey needs to be one of the following sizes: 128, 192 or 256 bits - in the example below it is 128 bit (= 16 bytes)
#  encryptionKey: xyz123wersdgf354
#  config:
#    # Change name of cursor parameter name
#    cursorName:
#    # Change name of pageSize parameter name
#    pageSizeName:
#    # Change name of current-page header name
#    currentPageName:
#    # Change name of next-page header name
#    nextPageName:
#    # Change name of previous-page header name
#    previousPageName:
#    # Change name of first-page header name
#    firstPageName:
#  # Possibility to change the default pagination size. If not specified all results will be returned as default
  defaultPageSize: 20

spring:
  application:
    name: DCSA-Backend
  r2dbc:
    url: r2dbc:postgresql://${db_hostname}
    name: dcsa_openapi
    properties:
      schema: dcsa_im_v3_0
    username: dcsa_db_owner
    password: 9c072fe8-c59c-11ea-b8d1-7b6577e9f3f5
    initialization-mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dcsa.eu.auth0.com/
  webflux:
    base-path: ${dcsa.url.prefix:}/v2
  mail:
    # Syntactically correct host name that will fail to resolve
    # in DNS.  The hostname should be guide most admins to the
    # proper solution. :)
    host: please-set-spring.mail.host-property-in-dsca-app.invalid
    # Leave username and password undefined here.
    # That should be a deployment specific option
    #
    # See https://www.baeldung.com/spring-email for some
    # examples.
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          # Leave port and auth undefined here.
          # That should be a deployment specific option
          starttls:
            # We use a strict default.
            enable: true
            required: true

auth0:
  audience: localhost
  enabled: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    # swagger-ui custom path
    path: /docs

dcsa:
  securityConfig:
    receiveNotificationEndpoint: "/notification-endpoints"
  webui:
    baseUrl: "NOT_SPECIFIED"
  email:
    from: noreply@dcsa.org
    timezone: "NOT_SPECIFIED"
    dateFormat: MM/dd/yyyy HH:mm
    debugEmail: false
    templates:
      timestampReceived:
        onlyForEventType:
          - OPERATIONS
        onlyForEventClassifierCode:
          - EST
          - REQ
        subject: Response requested on timestamp from vessel {{VESSEL_NAME}}.
        body: |
          <p>Vessel {{VESSEL_NAME}} // IMO{{VESSEL_IMO_NUMBER}} registered a new {{TIMESTAMP_TYPE}}. Your response is required.</p>
          <p>Please go to <a href="{{WEB_UI_LINK}}">{{WEB_UI_LINK}}</a> and response to the timestamp.</p>

  pendingEventService:
    # DCSA-OVS will process these.
    enabled: false
    backgroundTasks:
      processUnmappedEventQueue:
        cronSchedule: "-"
      processPendingEventQueue:
        cronSchedule: "-"

server:
  port: 9092
  error:
    include-binding-errors: on_param
    include-message: always

logging:
  level:
    root: INFO
    org:
      springframework:
        r2dbc: INFO

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
